name: api-image
services:

  api-image:
    profiles:
      - dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - 3001:3000
      - 9229:9229
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/api-image?authSource=admin
    volumes:
      - .:/workspace:cached
    networks:
      - network-api-image
    command: [ 'tail', '-f', '/dev/null' ]
  mongodb:
    image: mongo:latest
    ports:
      - ${MONGO_api_image_PORT:-27017}:27017    
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE=api-image
    networks:
        - network-api-image
        
networks:
  network-api-image:
